import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import CopyRIght from '../components/CopyRIght'
import Footer from '../components/Footer'
import Gallery from '../components/Gallery'
import Hero from '../components/Hero'
import Interview from '../components/Interview'
import Navbar from '../components/Navbar'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <>
      <Head>
        <title>TATOO STUDIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <About/>
      <Gallery/>
      <Skills/>
      <Interview/>
      <Contact/>
      <Footer/>
      <CopyRIght/>
    </>
  )
}
